import { Logger } from '../utils/logger';

const logger = new Logger('ERC20Generator');

export interface ERC20Config {
  name: string;
  symbol: string;
  totalSupply: string;
  decimals: number;
  
  buyTax?: number;
  sellTax?: number;
  transferTax?: number;
  
  liquidityPercent?: number;
  liquidityLockDays?: number;
  
  maxTransactionAmount?: string;
  maxWalletAmount?: string;
  tradingDelayEnabled?: boolean;
  blacklistEnabled?: boolean;
  
  mintable?: boolean;
  burnable?: boolean;
  pausable?: boolean;
  
  ownerAddress: string;
  renounceOwnership?: boolean;
}

export interface ERC20DeploymentData {
  contractCode: string;
  constructorArgs: string[];
  estimatedGas: string;
  deploymentInstructions: string[];
  securityWarnings: string[];
}

export class ERC20Generator {
  /**
   * Generate ERC-20 token contract code
   */
  generateContract(config: ERC20Config): ERC20DeploymentData {
    logger.info(`Generating ERC-20 contract: ${config.name} (${config.symbol})`);
    
    this.validateConfig(config);
    
    const contractCode = this.buildContractCode(config);
    
    const constructorArgs = this.buildConstructorArgs(config);
    
    const estimatedGas = this.estimateGas(config);
    
    const deploymentInstructions = this.generateDeploymentInstructions(config);
    
    const securityWarnings = this.generateSecurityWarnings(config);
    
    return {
      contractCode,
      constructorArgs,
      estimatedGas,
      deploymentInstructions,
      securityWarnings,
    };
  }
  
  /**
   * Validate ERC-20 configuration
   */
  private validateConfig(config: ERC20Config): void {
    if (!config.name || config.name.length === 0) {
      throw new Error('Token name is required');
    }
    
    if (!config.symbol || config.symbol.length === 0) {
      throw new Error('Token symbol is required');
    }
    
    if (!config.totalSupply || BigInt(config.totalSupply) <= 0) {
      throw new Error('Total supply must be greater than 0');
    }
    
    if (config.decimals < 0 || config.decimals > 18) {
      throw new Error('Decimals must be between 0 and 18');
    }
    
    if (!config.ownerAddress || !config.ownerAddress.startsWith('0x')) {
      throw new Error('Valid owner address is required');
    }
    
    if (config.buyTax && (config.buyTax < 0 || config.buyTax > 25)) {
      throw new Error('Buy tax must be between 0% and 25%');
    }
    
    if (config.sellTax && (config.sellTax < 0 || config.sellTax > 25)) {
      throw new Error('Sell tax must be between 0% and 25%');
    }
    
    if (config.transferTax && (config.transferTax < 0 || config.transferTax > 25)) {
      throw new Error('Transfer tax must be between 0% and 25%');
    }
  }
  
  /**
   * Build contract code
   */
  private buildContractCode(config: ERC20Config): string {
    const hasTaxes = config.buyTax || config.sellTax || config.transferTax;
    const hasAntiBot = config.maxTransactionAmount || config.maxWalletAmount || config.tradingDelayEnabled;
    
    let contractCode = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
${config.pausable ? 'import "@openzeppelin/contracts/security/Pausable.sol";' : ''}
${config.burnable ? 'import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable.sol";' : ''}

/**
 * @title ${config.name}
 * @dev ERC-20 Token generated by OnyxFlux
 */
contract ${this.sanitizeContractName(config.name)} is ERC20, Ownable${config.pausable ? ', Pausable' : ''}${config.burnable ? ', ERC20Burnable' : ''} {
    
    uint8 private _decimals = ${config.decimals};
    ${hasTaxes ? `
    uint256 public buyTax = ${config.buyTax || 0};
    uint256 public sellTax = ${config.sellTax || 0};
    uint256 public transferTax = ${config.transferTax || 0};
    address public taxWallet;
    ` : ''}
    ${hasAntiBot ? `
    uint256 public maxTransactionAmount = ${config.maxTransactionAmount || '0'};
    uint256 public maxWalletAmount = ${config.maxWalletAmount || '0'};
    ${config.tradingDelayEnabled ? 'mapping(address => uint256) private _lastTransferTimestamp;' : ''}
    ${config.blacklistEnabled ? 'mapping(address => bool) public blacklisted;' : ''}
    bool public tradingEnabled = false;
    ` : ''}
    
    mapping(address => bool) public isExcludedFromFees;
    mapping(address => bool) public isExcludedFromLimits;
    
    constructor() ERC20("${config.name}", "${config.symbol}") {
        _mint(msg.sender, ${config.totalSupply} * 10**decimals());
        ${hasTaxes ? 'taxWallet = msg.sender;' : ''}
        
        isExcludedFromFees[msg.sender] = true;
        isExcludedFromFees[address(this)] = true;
        isExcludedFromLimits[msg.sender] = true;
        isExcludedFromLimits[address(this)] = true;
    }
    
    function decimals() public view virtual override returns (uint8) {
        return _decimals;
    }
    ${hasTaxes ? `
    
    function setTaxes(uint256 _buyTax, uint256 _sellTax, uint256 _transferTax) external onlyOwner {
        require(_buyTax <= 25 && _sellTax <= 25 && _transferTax <= 25, "Tax too high");
        buyTax = _buyTax;
        sellTax = _sellTax;
        transferTax = _transferTax;
    }
    
    function setTaxWallet(address _taxWallet) external onlyOwner {
        require(_taxWallet != address(0), "Invalid address");
        taxWallet = _taxWallet;
    }
    ` : ''}
    ${hasAntiBot ? `
    
    function setMaxTransactionAmount(uint256 _maxTxAmount) external onlyOwner {
        maxTransactionAmount = _maxTxAmount;
    }
    
    function setMaxWalletAmount(uint256 _maxWalletAmount) external onlyOwner {
        maxWalletAmount = _maxWalletAmount;
    }
    
    function enableTrading() external onlyOwner {
        tradingEnabled = true;
    }
    ${config.blacklistEnabled ? `
    
    function setBlacklist(address account, bool value) external onlyOwner {
        blacklisted[account] = value;
    }
    
    function setBlacklistBatch(address[] calldata accounts, bool value) external onlyOwner {
        for (uint256 i = 0; i < accounts.length; i++) {
            blacklisted[accounts[i]] = value;
        }
    }
    ` : ''}
    ` : ''}
    
    function setExcludedFromFees(address account, bool excluded) external onlyOwner {
        isExcludedFromFees[account] = excluded;
    }
    
    function setExcludedFromLimits(address account, bool excluded) external onlyOwner {
        isExcludedFromLimits[account] = excluded;
    }
    ${config.mintable ? `
    
    function mint(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }
    ` : ''}
    ${config.pausable ? `
    
    function pause() external onlyOwner {
        _pause();
    }
    
    function unpause() external onlyOwner {
        _unpause();
    }
    ` : ''}
    
    function _transfer(
        address from,
        address to,
        uint256 amount
    ) internal override${config.pausable ? ' whenNotPaused' : ''} {
        require(from != address(0), "ERC20: transfer from zero address");
        require(to != address(0), "ERC20: transfer to zero address");
        ${hasAntiBot ? `
        require(tradingEnabled || isExcludedFromLimits[from] || isExcludedFromLimits[to], "Trading not enabled");
        ${config.blacklistEnabled ? 'require(!blacklisted[from] && !blacklisted[to], "Blacklisted address");' : ''}
        ${config.tradingDelayEnabled ? `
        if (!isExcludedFromLimits[from]) {
            require(block.timestamp >= _lastTransferTimestamp[from] + 1, "Transfer delay active");
            _lastTransferTimestamp[from] = block.timestamp;
        }
        ` : ''}
        
        if (!isExcludedFromLimits[from] && !isExcludedFromLimits[to]) {
            if (maxTransactionAmount > 0) {
                require(amount <= maxTransactionAmount, "Exceeds max transaction amount");
            }
            if (maxWalletAmount > 0 && to != address(0)) {
                require(balanceOf(to) + amount <= maxWalletAmount, "Exceeds max wallet amount");
            }
        }
        ` : ''}
        
        uint256 taxAmount = 0;
        ${hasTaxes ? `
        
        if (!isExcludedFromFees[from] && !isExcludedFromFees[to]) {
            if (transferTax > 0) {
                taxAmount = (amount * transferTax) / 100;
            }
            
            if (taxAmount > 0) {
                super._transfer(from, taxWallet, taxAmount);
            }
        }
        ` : ''}
        
        super._transfer(from, to, amount - taxAmount);
    }
    ${config.renounceOwnership ? `
    
    function renounceOwnershipPermanently() external onlyOwner {
        renounceOwnership();
    }
    ` : ''}
}
`;
    
    return contractCode;
  }
  
  /**
   * Sanitize contract name (remove spaces, special chars)
   */
  private sanitizeContractName(name: string): string {
    return name.replace(/[^a-zA-Z0-9]/g, '');
  }
  
  /**
   * Build constructor arguments
   */
  private buildConstructorArgs(config: ERC20Config): string[] {
    return [];
  }
  
  /**
   * Estimate gas for deployment
   */
  private estimateGas(config: ERC20Config): string {
    let gasEstimate = 2000000;
    
    if (config.buyTax || config.sellTax || config.transferTax) {
      gasEstimate += 500000;
    }
    
    if (config.maxTransactionAmount || config.maxWalletAmount) {
      gasEstimate += 300000;
    }
    
    if (config.mintable) {
      gasEstimate += 100000;
    }
    
    if (config.burnable) {
      gasEstimate += 100000;
    }
    
    if (config.pausable) {
      gasEstimate += 150000;
    }
    
    return gasEstimate.toString();
  }
  
  /**
   * Generate deployment instructions
   */
  private generateDeploymentInstructions(config: ERC20Config): string[] {
    const instructions = [
      '1. Install dependencies: npm install @openzeppelin/contracts',
      '2. Compile the contract using Hardhat or Remix',
      '3. Connect your wallet (MetaMask, WalletConnect, etc.)',
      '4. Deploy the contract to your desired network',
      `5. Estimated gas: ${this.estimateGas(config)} units`,
      '6. After deployment, verify the contract on block explorer',
    ];
    
    if (config.buyTax || config.sellTax || config.transferTax) {
      instructions.push('7. Set tax wallet address using setTaxWallet()');
    }
    
    if (config.maxTransactionAmount || config.maxWalletAmount) {
      instructions.push('8. Enable trading when ready using enableTrading()');
    }
    
    if (config.liquidityPercent && config.liquidityPercent > 0) {
      instructions.push(`9. Add ${config.liquidityPercent}% of supply to liquidity pool`);
    }
    
    if (config.liquidityLockDays && config.liquidityLockDays > 0) {
      instructions.push(`10. Lock liquidity for ${config.liquidityLockDays} days using a trusted locker`);
    }
    
    if (config.renounceOwnership) {
      instructions.push('11. FINAL STEP: Renounce ownership using renounceOwnershipPermanently() - THIS IS IRREVERSIBLE');
    }
    
    return instructions;
  }
  
  /**
   * Generate security warnings
   */
  private generateSecurityWarnings(config: ERC20Config): string[] {
    const warnings: string[] = [];
    
    if (config.mintable && !config.renounceOwnership) {
      warnings.push('⚠️ CRITICAL: Mintable tokens without renounced ownership can be inflated by owner');
    }
    
    if ((config.buyTax || config.sellTax || config.transferTax) && !config.renounceOwnership) {
      warnings.push('⚠️ WARNING: Owner can change tax rates at any time - consider renouncing ownership');
    }
    
    if (config.blacklistEnabled) {
      warnings.push('⚠️ WARNING: Blacklist feature allows owner to block addresses from trading');
    }
    
    if (config.pausable) {
      warnings.push('⚠️ WARNING: Pausable feature allows owner to freeze all transfers');
    }
    
    if (!config.liquidityLockDays || config.liquidityLockDays < 30) {
      warnings.push('⚠️ CRITICAL: Liquidity should be locked for at least 30 days to prevent rug pulls');
    }
    
    if (config.maxTransactionAmount || config.maxWalletAmount) {
      warnings.push('✓ GOOD: Anti-whale limits are enabled');
    }
    
    if (config.renounceOwnership) {
      warnings.push('✓ GOOD: Ownership will be renounced - contract becomes immutable');
    }
    
    return warnings;
  }
  
  /**
   * Generate deployment bytecode (simplified)
   */
  generateBytecode(config: ERC20Config): string {
    return '0x608060405234801561001057600080fd5b50...'; // Truncated for brevity
  }
  
  /**
   * Get recommended settings for safe token
   */
  static getRecommendedSafeSettings(): Partial<ERC20Config> {
    return {
      buyTax: 0,
      sellTax: 0,
      transferTax: 0,
      maxTransactionAmount: '0', // No limit
      maxWalletAmount: '0', // No limit
      tradingDelayEnabled: false,
      blacklistEnabled: false,
      mintable: false,
      burnable: true,
      pausable: false,
      renounceOwnership: true,
      liquidityLockDays: 365,
    };
  }
}
