import { Logger } from '../utils/logger';

const logger = new Logger('ERC721Generator');

export interface ERC721Config {
  name: string;
  symbol: string;
  maxSupply: number;
  
  mintPrice?: string;
  maxMintPerWallet?: number;
  publicMintEnabled?: boolean;
  
  baseURI: string;
  placeholderURI?: string;
  revealEnabled?: boolean;
  
  royaltyPercent?: number;
  royaltyReceiver?: string;
  
  burnable?: boolean;
  pausable?: boolean;
  enumerable?: boolean;
  
  ownerAddress: string;
  renounceOwnership?: boolean;
}

export interface ERC721DeploymentData {
  contractCode: string;
  constructorArgs: string[];
  estimatedGas: string;
  deploymentInstructions: string[];
  securityWarnings: string[];
  metadataTemplate: object;
}

export class ERC721Generator {
  /**
   * Generate ERC-721 NFT contract code
   */
  generateContract(config: ERC721Config): ERC721DeploymentData {
    logger.info(`Generating ERC-721 contract: ${config.name} (${config.symbol})`);
    
    this.validateConfig(config);
    
    const contractCode = this.buildContractCode(config);
    
    const constructorArgs = this.buildConstructorArgs(config);
    
    const estimatedGas = this.estimateGas(config);
    
    const deploymentInstructions = this.generateDeploymentInstructions(config);
    
    const securityWarnings = this.generateSecurityWarnings(config);
    
    const metadataTemplate = this.generateMetadataTemplate(config);
    
    return {
      contractCode,
      constructorArgs,
      estimatedGas,
      deploymentInstructions,
      securityWarnings,
      metadataTemplate,
    };
  }
  
  /**
   * Validate ERC-721 configuration
   */
  private validateConfig(config: ERC721Config): void {
    if (!config.name || config.name.length === 0) {
      throw new Error('NFT name is required');
    }
    
    if (!config.symbol || config.symbol.length === 0) {
      throw new Error('NFT symbol is required');
    }
    
    if (!config.maxSupply || config.maxSupply <= 0) {
      throw new Error('Max supply must be greater than 0');
    }
    
    if (!config.baseURI || config.baseURI.length === 0) {
      throw new Error('Base URI is required');
    }
    
    if (!config.ownerAddress || !config.ownerAddress.startsWith('0x')) {
      throw new Error('Valid owner address is required');
    }
    
    if (config.royaltyPercent && (config.royaltyPercent < 0 || config.royaltyPercent > 10)) {
      throw new Error('Royalty percent must be between 0% and 10%');
    }
    
    if (config.royaltyPercent && !config.royaltyReceiver) {
      throw new Error('Royalty receiver address is required when royalty is set');
    }
  }
  
  /**
   * Build contract code
   */
  private buildContractCode(config: ERC721Config): string {
    const hasRoyalty = config.royaltyPercent && config.royaltyPercent > 0;
    const hasMinting = config.mintPrice && parseFloat(config.mintPrice) > 0;
    
    let contractCode = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
${config.enumerable ? 'import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";' : ''}
${hasRoyalty ? 'import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Royalty.sol";' : ''}
import "@openzeppelin/contracts/access/Ownable.sol";
${config.pausable ? 'import "@openzeppelin/contracts/security/Pausable.sol";' : ''}
${config.burnable ? 'import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Burnable.sol";' : ''}
import "@openzeppelin/contracts/utils/Counters.sol";

/**
 * @title ${config.name}
 * @dev ERC-721 NFT Collection generated by OnyxFlux
 */
contract ${this.sanitizeContractName(config.name)} is 
    ERC721${config.enumerable ? ', ERC721Enumerable' : ''}${hasRoyalty ? ', ERC721Royalty' : ''}, 
    Ownable${config.pausable ? ', Pausable' : ''}${config.burnable ? ', ERC721Burnable' : ''} 
{
    using Counters for Counters.Counter;
    
    Counters.Counter private _tokenIdCounter;
    
    uint256 public constant MAX_SUPPLY = ${config.maxSupply};
    ${hasMinting ? `uint256 public mintPrice = ${config.mintPrice};` : ''}
    ${config.maxMintPerWallet ? `uint256 public maxMintPerWallet = ${config.maxMintPerWallet};` : ''}
    ${config.publicMintEnabled !== undefined ? `bool public publicMintEnabled = ${config.publicMintEnabled};` : ''}
    
    string private _baseTokenURI = "${config.baseURI}";
    ${config.revealEnabled ? `
    string private _placeholderURI = "${config.placeholderURI || ''}";
    bool public revealed = false;
    ` : ''}
    
    ${config.maxMintPerWallet ? 'mapping(address => uint256) public mintedPerWallet;' : ''}
    
    constructor() ERC721("${config.name}", "${config.symbol}") {
        ${hasRoyalty ? `_setDefaultRoyalty(${config.royaltyReceiver}, ${Math.floor((config.royaltyPercent || 0) * 100)});` : ''}
    }
    
    function _baseURI() internal view virtual override returns (string memory) {
        return _baseTokenURI;
    }
    
    function setBaseURI(string memory baseURI) external onlyOwner {
        _baseTokenURI = baseURI;
    }
    ${config.revealEnabled ? `
    
    function reveal() external onlyOwner {
        revealed = true;
    }
    
    function setPlaceholderURI(string memory placeholderURI) external onlyOwner {
        _placeholderURI = placeholderURI;
    }
    
    function tokenURI(uint256 tokenId) public view virtual override returns (string memory) {
        require(_exists(tokenId), "Token does not exist");
        
        if (!revealed) {
            return _placeholderURI;
        }
        
        return super.tokenURI(tokenId);
    }
    ` : ''}
    ${hasMinting ? `
    
    function setMintPrice(uint256 _mintPrice) external onlyOwner {
        mintPrice = _mintPrice;
    }
    ${config.publicMintEnabled !== undefined ? `
    
    function setPublicMintEnabled(bool _enabled) external onlyOwner {
        publicMintEnabled = _enabled;
    }
    ` : ''}
    
    function mint(uint256 quantity) external payable${config.pausable ? ' whenNotPaused' : ''} {
        require(publicMintEnabled, "Public mint not enabled");
        require(quantity > 0, "Quantity must be greater than 0");
        require(_tokenIdCounter.current() + quantity <= MAX_SUPPLY, "Exceeds max supply");
        require(msg.value >= mintPrice * quantity, "Insufficient payment");
        ${config.maxMintPerWallet ? `
        require(mintedPerWallet[msg.sender] + quantity <= maxMintPerWallet, "Exceeds max mint per wallet");
        mintedPerWallet[msg.sender] += quantity;
        ` : ''}
        
        for (uint256 i = 0; i < quantity; i++) {
            uint256 tokenId = _tokenIdCounter.current();
            _tokenIdCounter.increment();
            _safeMint(msg.sender, tokenId);
        }
    }
    ` : ''}
    
    function ownerMint(address to, uint256 quantity) external onlyOwner {
        require(quantity > 0, "Quantity must be greater than 0");
        require(_tokenIdCounter.current() + quantity <= MAX_SUPPLY, "Exceeds max supply");
        
        for (uint256 i = 0; i < quantity; i++) {
            uint256 tokenId = _tokenIdCounter.current();
            _tokenIdCounter.increment();
            _safeMint(to, tokenId);
        }
    }
    
    function totalSupply() public view returns (uint256) {
        return _tokenIdCounter.current();
    }
    ${hasRoyalty ? `
    
    function setDefaultRoyalty(address receiver, uint96 feeNumerator) external onlyOwner {
        _setDefaultRoyalty(receiver, feeNumerator);
    }
    
    function setTokenRoyalty(uint256 tokenId, address receiver, uint96 feeNumerator) external onlyOwner {
        _setTokenRoyalty(tokenId, receiver, feeNumerator);
    }
    ` : ''}
    ${config.pausable ? `
    
    function pause() external onlyOwner {
        _pause();
    }
    
    function unpause() external onlyOwner {
        _unpause();
    }
    ` : ''}
    ${hasMinting ? `
    
    function withdraw() external onlyOwner {
        uint256 balance = address(this).balance;
        require(balance > 0, "No balance to withdraw");
        payable(owner()).transfer(balance);
    }
    ` : ''}
    
    ${config.enumerable ? `
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId,
        uint256 batchSize
    ) internal override(ERC721, ERC721Enumerable)${config.pausable ? ' whenNotPaused' : ''} {
        super._beforeTokenTransfer(from, to, tokenId, batchSize);
    }
    ` : config.pausable ? `
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId,
        uint256 batchSize
    ) internal override whenNotPaused {
        super._beforeTokenTransfer(from, to, tokenId, batchSize);
    }
    ` : ''}
    
    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(ERC721${config.enumerable ? ', ERC721Enumerable' : ''}${hasRoyalty ? ', ERC721Royalty' : ''})
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}
`;
    
    return contractCode;
  }
  
  /**
   * Sanitize contract name
   */
  private sanitizeContractName(name: string): string {
    return name.replace(/[^a-zA-Z0-9]/g, '');
  }
  
  /**
   * Build constructor arguments
   */
  private buildConstructorArgs(config: ERC721Config): string[] {
    return [];
  }
  
  /**
   * Estimate gas for deployment
   */
  private estimateGas(config: ERC721Config): string {
    let gasEstimate = 3000000;
    
    if (config.enumerable) {
      gasEstimate += 500000;
    }
    
    if (config.royaltyPercent) {
      gasEstimate += 200000;
    }
    
    if (config.pausable) {
      gasEstimate += 150000;
    }
    
    if (config.burnable) {
      gasEstimate += 100000;
    }
    
    return gasEstimate.toString();
  }
  
  /**
   * Generate deployment instructions
   */
  private generateDeploymentInstructions(config: ERC721Config): string[] {
    const instructions = [
      '1. Install dependencies: npm install @openzeppelin/contracts',
      '2. Prepare metadata files and upload to IPFS or hosting service',
      '3. Update baseURI in contract with your metadata location',
      '4. Compile the contract using Hardhat or Remix',
      '5. Connect your wallet (MetaMask, WalletConnect, etc.)',
      '6. Deploy the contract to your desired network',
      `7. Estimated gas: ${this.estimateGas(config)} units`,
      '8. After deployment, verify the contract on block explorer',
    ];
    
    if (config.revealEnabled) {
      instructions.push('9. Upload placeholder metadata before minting');
      instructions.push('10. Call reveal() when ready to reveal actual metadata');
    }
    
    if (config.mintPrice && parseFloat(config.mintPrice) > 0) {
      instructions.push('11. Enable public minting using setPublicMintEnabled(true)');
    }
    
    if (config.renounceOwnership) {
      instructions.push('12. FINAL STEP: Renounce ownership - THIS IS IRREVERSIBLE');
    }
    
    return instructions;
  }
  
  /**
   * Generate security warnings
   */
  private generateSecurityWarnings(config: ERC721Config): string[] {
    const warnings: string[] = [];
    
    if (!config.renounceOwnership) {
      warnings.push('⚠️ WARNING: Owner retains control - can change baseURI and mint tokens');
    }
    
    if (config.pausable) {
      warnings.push('⚠️ WARNING: Pausable feature allows owner to freeze all transfers');
    }
    
    if (!config.maxMintPerWallet) {
      warnings.push('⚠️ WARNING: No mint limit per wallet - whales can mint entire supply');
    }
    
    if (config.royaltyPercent && config.royaltyPercent > 0) {
      warnings.push(`✓ GOOD: ${config.royaltyPercent}% royalty enabled for secondary sales`);
    }
    
    if (config.revealEnabled) {
      warnings.push('✓ GOOD: Delayed reveal prevents sniping of rare NFTs');
    }
    
    if (config.maxMintPerWallet) {
      warnings.push(`✓ GOOD: Max ${config.maxMintPerWallet} mints per wallet prevents hoarding`);
    }
    
    return warnings;
  }
  
  /**
   * Generate metadata template
   */
  private generateMetadataTemplate(config: ERC721Config): object {
    return {
      name: `${config.name} #1`,
      description: `Part of the ${config.name} collection`,
      image: 'ipfs://YOUR_IMAGE_CID/1.png',
      external_url: 'https://your-website.com',
      attributes: [
        {
          trait_type: 'Background',
          value: 'Blue',
        },
        {
          trait_type: 'Rarity',
          value: 'Common',
        },
      ],
    };
  }
  
  /**
   * Get recommended settings for safe NFT
   */
  static getRecommendedSafeSettings(): Partial<ERC721Config> {
    return {
      maxMintPerWallet: 10,
      publicMintEnabled: false,
      revealEnabled: true,
      royaltyPercent: 5,
      burnable: true,
      pausable: false,
      enumerable: true,
      renounceOwnership: false, // Keep control for metadata updates
    };
  }
}
